# Site settings
title: "Shubhdeep Singh's Portfolio"
description: "Security Operations & Threat Intelligence Professional Portfolio"
baseurl: "/shubhdeepsingh" # Subdirectory path
url: "https://shubamarora.github.io/shubhdeepsingh/" # Your site URL

# Author information
author:
  name: "Shubhdeep Singh"
  tagline: "Security Operations & Threat Intelligence Professional"
  bio: "I am an aspiring Cybersecurity Analyst with hands-on experience in SOC operations, incident response, and threat hunting. I have completed industry-recognized certifications such as ISO/IEC 27001 Information Security Associate and TryHackMe SOC Level 1 & 2, which have equipped me with practical skills in SIEM monitoring, log analysis, and malware investigation. I am passionate about protecting organizations from cyber threats and continuously enhancing my technical expertise."
  email: "shubamarora7@gmail.com"
  linkedin: "https://www.linkedin.com/in/shubhdeep-singh-w137w/"
  github: "https://github.com/shubamarora"

# Build settings
markdown: kramdown
permalink: pretty

# Debug settings
verbose: true
incremental: false

# Exclude from processing
exclude:
  - README.md
  - Gemfile

  - Gemfile.lock


